# Generated by Django 5.0 on 2023-12-18 08:07

import authtoken.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.CharField(default=authtoken.models.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('org_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=10)),
                ('user_token', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.organization')),
            ],
        ),
    ]
